export const CLEAR_FORM_USER_ACTION = 'CLEAR_FORM_USER_ACTION';
export const LOGIN_USER_ACTION = 'LOGIN_USER_ACTION';
export const LOGOUT_USER_ACTION = 'LOGOUT_USER_ACTION';
export const UPDATE_FORM_USER_ACTION = 'UPDATE_FORM_USER_ACTION';
export const FORM_ERROR_USER_ACTION = 'FORM_ERROR_USER_ACTION';
