export const CLEAR_PASSWORDS_USER_ACTION = 'CLEAR_PASSWORDS_USER_ACTION';
export const LOGIN_USER_ACTION = 'LOGIN_USER_ACTION';
export const UPDATE_FORM_USER_ACTION = 'UPDATE_FORM_USER_ACTION';
export const UPDATE_USER_ACTION = 'UPDATE_USER_ACTION'
